// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ProofStatus string

const (
	ProofStatusUnresolved ProofStatus = "unresolved"
	ProofStatusPass       ProofStatus = "pass"
	ProofStatusFail       ProofStatus = "fail"
)

func (e *ProofStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProofStatus(s)
	case string:
		*e = ProofStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProofStatus: %T", src)
	}
	return nil
}

type NullProofStatus struct {
	ProofStatus ProofStatus
	Valid       bool // Valid is true if ProofStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProofStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProofStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProofStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProofStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProofStatus), nil
}

type AccessKey struct {
	ID      int32
	TrackID string
	PubKey  string
}

type CoreAppState struct {
	BlockHeight int64
	AppHash     []byte
	CreatedAt   pgtype.Timestamp
}

type CoreBlock struct {
	Rowid     int64
	Height    int64
	ChainID   string
	Hash      string
	Proposer  string
	CreatedAt pgtype.Timestamp
}

type CoreDeal struct {
	Address     string
	ErnAddress  string
	EntityType  string
	EntityIndex int32
	TxHash      string
	BlockHeight int64
	CreatedAt   pgtype.Timestamp
}

type CoreErn struct {
	ID                 int64
	Address            string
	Index              int64
	TxHash             string
	Sender             string
	MessageControlType int16
	RawMessage         []byte
	RawAcknowledgment  []byte
	BlockHeight        int64
}

type CoreEtlTx struct {
	ID          int64
	BlockHeight int64
	TxIndex     int32
	TxHash      string
	TxType      string
	TxData      []byte
	CreatedAt   pgtype.Timestamptz
}

type CoreEtlTxDuplicate struct {
	ID            int64
	TxHash        string
	TableName     string
	DuplicateType string
	CreatedAt     pgtype.Timestamptz
}

type CoreEtlTxManageEntity struct {
	ID         int64
	TxHash     string
	UserID     int64
	EntityType string
	EntityID   int64
	Action     string
	Metadata   string
	Signature  string
	Signer     string
	Nonce      string
	CreatedAt  pgtype.Timestamptz
}

type CoreEtlTxPlay struct {
	ID        int64
	TxHash    string
	UserID    string
	TrackID   string
	PlayedAt  pgtype.Timestamptz
	Signature string
	City      pgtype.Text
	Region    pgtype.Text
	Country   pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type CoreEtlTxSlaRollup struct {
	ID         int64
	TxHash     string
	BlockStart int64
	BlockEnd   int64
	Timestamp  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type CoreEtlTxStorageProof struct {
	ID              int64
	TxHash          string
	Height          int64
	Address         string
	Cid             pgtype.Text
	ProofSignature  []byte
	ProverAddresses []string
	CreatedAt       pgtype.Timestamptz
}

type CoreEtlTxStorageProofVerification struct {
	ID        int64
	TxHash    string
	Height    int64
	Proof     []byte
	CreatedAt pgtype.Timestamptz
}

type CoreEtlTxValidatorDeregistration struct {
	ID           int64
	TxHash       string
	CometAddress string
	PubKey       []byte
	CreatedAt    pgtype.Timestamptz
}

type CoreEtlTxValidatorRegistration struct {
	ID           int64
	TxHash       string
	Endpoint     string
	CometAddress string
	EthBlock     string
	NodeType     string
	SpID         string
	PubKey       []byte
	Power        int64
	CreatedAt    pgtype.Timestamptz
}

type CoreMead struct {
	ID                int64
	Address           string
	TxHash            string
	Index             int64
	Sender            string
	ResourceAddresses []string
	ReleaseAddresses  []string
	RawMessage        []byte
	RawAcknowledgment []byte
	BlockHeight       int64
}

type CoreParty struct {
	Address     string
	ErnAddress  string
	EntityType  string
	EntityIndex int32
	TxHash      string
	BlockHeight int64
	CreatedAt   pgtype.Timestamp
}

type CorePie struct {
	ID                int64
	Address           string
	TxHash            string
	Index             int64
	Sender            string
	PartyAddresses    []string
	RawMessage        []byte
	RawAcknowledgment []byte
	BlockHeight       int64
}

type CoreRelease struct {
	Address     string
	ErnAddress  string
	EntityType  string
	EntityIndex int32
	TxHash      string
	BlockHeight int64
	CreatedAt   pgtype.Timestamp
}

type CoreResource struct {
	Address     string
	ErnAddress  string
	EntityType  string
	EntityIndex int32
	TxHash      string
	BlockHeight int64
	CreatedAt   pgtype.Timestamp
}

type CoreReward struct {
	ID               int64
	Address          string
	Index            int64
	TxHash           string
	Sender           string
	RewardID         string
	Name             string
	Amount           int64
	ClaimAuthorities []string
	RawMessage       []byte
	BlockHeight      int64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type CoreTransaction struct {
	Rowid       int64
	BlockID     int64
	Index       int32
	TxHash      string
	Transaction []byte
	CreatedAt   pgtype.Timestamp
}

type CoreTxStat struct {
	ID          int32
	TxType      string
	TxHash      string
	BlockHeight int64
	CreatedAt   pgtype.Timestamp
}

type CoreUpload struct {
	ID                 int64
	UploaderAddress    string
	Cid                string
	TranscodedCid      string
	Upid               string
	UploadSignature    string
	ValidatorAddress   string
	ValidatorSignature string
	TxHash             string
	BlockHeight        int64
}

type CoreValidator struct {
	Rowid        int32
	PubKey       string
	Endpoint     string
	EthAddress   string
	CometAddress string
	EthBlock     string
	NodeType     string
	SpID         string
	CometPubKey  string
}

type ManagementKey struct {
	ID      int32
	TrackID string
	Address string
}

type SlaNodeReport struct {
	ID             int32
	Address        string
	BlocksProposed int32
	SlaRollupID    pgtype.Int4
}

type SlaRollup struct {
	ID         int32
	TxHash     string
	BlockStart int64
	BlockEnd   int64
	Time       pgtype.Timestamp
}

type SoundRecording struct {
	ID               int32
	SoundRecordingID string
	TrackID          string
	Cid              string
	EncodingDetails  pgtype.Text
}

type StorageProof struct {
	ID              int32
	BlockHeight     int64
	Address         string
	Cid             pgtype.Text
	ProofSignature  pgtype.Text
	Proof           pgtype.Text
	ProverAddresses []string
	Status          ProofStatus
}

type StorageProofPeer struct {
	ID              int32
	BlockHeight     int64
	ProverAddresses []string
}

type TrackRelease struct {
	ID      int32
	TrackID string
}

type ValidatorHistory struct {
	Rowid        int32
	Endpoint     string
	EthAddress   string
	CometAddress string
	SpID         int64
	ServiceType  string
	EventType    ValidatorEventType
	EventTime    pgtype.Timestamp
	EventBlock   int64
}
